export const ADD_TASK = 'ADD_TASK';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const GET_FILTER_TASKS = "GET_FILTER_TASKS";
export const DELETE_TASK = "DELETE_TASK";
// export const UPDATE_STATUS_FILTER = "UPDATE_STATUS_FILTER";